# openapi.yaml
openapi: 3.0.0
info:
  title: Webhook API
  version: 1.0.0
paths:
  /:
    post:
      summary: Webhook endpoint
      operationId: webhook
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized