# .github/workflows/deploy.yml
name: Deploy

on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: ${{ vars.GCP_PROJECT_ID }}
  GCP_REGION: ${{ vars.GCP_REGION }}
  GOOGLE_DEFAULT_CALENDAR_ID: ${{ vars.GOOGLE_DEFAULT_CALENDAR_ID }}
  GOOGLE_APPSHEET_APP_ID: ${{ vars.GOOGLE_APPSHEET_APP_ID }}
  GCP_GOOGLE_CALENDAR_SERVICE_ACCOUNT_EMAIL: ${{ vars.GCP_GOOGLE_CALENDAR_SERVICE_ACCOUNT_EMAIL }}
  HEADER_SOURCE_TO_PASS: ${{ vars.HEADER_SOURCE_TO_PASS }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install zip utility
      run: 
        sudo apt-get install -y zip

    - name: Prepare Function Source
      run: |
        cd functions
        zip -r ../terraform/function-source.zip .

    - name: Install Terraform
      run: |
        sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt-get update && sudo apt-get install -y terraform

    - name: Terraform Init
      run: terraform init
      working-directory: terraform \
          -var="GCP_PROJECT_ID=${{ env.GCP_PROJECT_ID }}" \
          -var="GCP_REGION=${{ env.GCP_REGION }}" \
          -var="GOOGLE_DEFAULT_CALENDAR_ID=${{ env.GOOGLE_DEFAULT_CALENDAR_ID }}" \
          -var="HEADER_SOURCE_TO_PASS=${{ env.HEADER_SOURCE_TO_PASS }}"
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
          -var="GCP_PROJECT_ID=${{ env.GCP_PROJECT_ID }}" \
          -var="GCP_REGION=${{ env.GCP_REGION }}" \
          -var="GOOGLE_DEFAULT_CALENDAR_ID=${{ env.GOOGLE_DEFAULT_CALENDAR_ID }}" \
          -var="HEADER_SOURCE_TO_PASS=${{ env.HEADER_SOURCE_TO_PASS }}"
      working-directory: terraform
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        GOOGLE_APPSHEET_ACCESS_KEY: ${{ secrets.GOOGLE_APPSHEET_ACCESS_KEY }}

    - name: Clean up
      run: rm gcp_sa_key.json

